# Generated by Django 5.0.4 on 2024-05-13 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('ejecutivo', 'Ejecutivo'), ('cliente', 'Cliente')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('area', models.CharField(choices=[('ejecutivo', 'Ejecutivo Telefonico'), ('soporte', 'Soporte'), ('cliente', 'Atencion al Cliente'), ('nivel2', 'Soporte Nivel 2')], max_length=255)),
                ('tipo', models.CharField(choices=[('incidente', 'Incidente'), ('solicitud', 'Solicitud'), ('cambio', 'Cambio')], max_length=255)),
                ('criticidad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('solucionado', 'Solucionado'), ('validado', 'Validado'), ('cerrado', 'Cerrado')], max_length=255)),
                ('descripcion', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_creados', to='core.usuario')),
                ('ejecutivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_asignados', to='core.usuario')),
            ],
        ),
    ]
