# Generated by Django 4.2.8 on 2024-06-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='usuario',
            new_name='user',
        ),
    ]
