# Generated by Django 5.0.4 on 2024-06-11 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstadoTicket',
            new_name='Estado',
        ),
    ]
