# Generated by Django 4.2.8 on 2024-07-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_comentarios_ticket_alter_comentarios_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='comentario',
            field=models.TextField(blank=True, max_length=255, verbose_name='Comentario'),
        ),
    ]
