# Generated by Django 5.0.4 on 2024-05-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='area',
            field=models.CharField(choices=[('Ejecutivo', 'Ejecutivo Telefonico'), ('Soporte', 'Soporte'), ('Cliente', 'Atencion al Cliente'), ('Soporte Nivel 2', 'Soporte Nivel 2')], max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='criticidad',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Solucionado', 'Solucionado'), ('Validado', 'Validado'), ('Cerrado', 'Cerrado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tipo',
            field=models.CharField(choices=[('Incidente', 'Incidente'), ('Solicitud', 'Solicitud'), ('Cambio', 'Cambio')], max_length=255),
        ),
    ]
