# Generated by Django 5.0.4 on 2024-06-27 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_alter_profile_is_active_alter_profile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fecha_cierre',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Rol'),
        ),
    ]
