# Generated by Django 5.0.4 on 2024-05-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ticket_area_alter_ticket_criticidad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
