# Generated by Django 5.0.4 on 2024-07-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profile_group'),
        ('core', '0006_ticket_fecha_cierre_alter_profile_group'),
    ]

    operations = [
    ]
