# Generated by Django 5.0.4 on 2024-06-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_ticket_area_alter_ticket_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Criticidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_criticidad', models.CharField(max_length=255)),
            ],
        ),
    ]
